DROP INDEX IF EXISTS idx_meeting_teachers_name;
DROP INDEX IF EXISTS idx_programs_status_publish;
DELETE FROM role_permissions WHERE permission_id IN (SELECT id FROM permissions WHERE code IN ('program:read','program:write','meeting:write'));
DELETE FROM permissions WHERE code IN ('program:read','program:write','meeting:write');
DROP TABLE IF EXISTS meeting_teachers;
ALTER TABLE meetings DROP COLUMN IF EXISTS attendance_closes_at;
ALTER TABLE meetings DROP COLUMN IF EXISTS attendance_opens_at;
ALTER TABLE meetings DROP COLUMN IF EXISTS audience_group;
ALTER TABLE meetings DROP COLUMN IF EXISTS material;
ALTER TABLE meetings DROP COLUMN IF EXISTS theme;
ALTER TABLE meetings DROP CONSTRAINT IF EXISTS meetings_status_check;
ALTER TABLE meetings ADD CONSTRAINT meetings_status_check CHECK (status IN ('SCHEDULED','COMPLETED','CANCELLED'));
ALTER TABLE meetings ALTER COLUMN status SET DEFAULT 'SCHEDULED';
ALTER TABLE batches DROP COLUMN IF EXISTS capacity;
ALTER TABLE batches DROP COLUMN IF EXISTS registration_close_at;
ALTER TABLE batches DROP COLUMN IF EXISTS registration_open_at;
DROP TABLE IF EXISTS program_features;
ALTER TABLE programs DROP COLUMN IF EXISTS publish_at;
ALTER TABLE programs DROP COLUMN IF EXISTS capacity;
ALTER TABLE programs DROP COLUMN IF EXISTS pic_name;
ALTER TABLE programs DROP COLUMN IF EXISTS location;
ALTER TABLE programs DROP COLUMN IF EXISTS category;
ALTER TABLE programs DROP CONSTRAINT IF EXISTS programs_status_check;
ALTER TABLE programs ADD CONSTRAINT programs_status_check CHECK (status IN ('ACTIVE','INACTIVE','ARCHIVED'));
ALTER TABLE programs ALTER COLUMN status SET DEFAULT 'ACTIVE';
