BEGIN;
ALTER TABLE knowledge_documents DROP CONSTRAINT IF EXISTS knowledge_documents_status_check;
ALTER TABLE knowledge_documents ALTER COLUMN status SET DEFAULT 'ACTIVE';
ALTER TABLE knowledge_documents ADD CONSTRAINT knowledge_documents_status_check CHECK(status IN('ACTIVE','ARCHIVED'));
ALTER TABLE knowledge_documents DROP COLUMN IF EXISTS expires_at, DROP COLUMN IF EXISTS effective_at, DROP COLUMN IF EXISTS purpose, DROP COLUMN IF EXISTS description;
DROP TABLE IF EXISTS app_settings;
DROP INDEX IF EXISTS idx_announcements_status_publish;
ALTER TABLE announcements DROP COLUMN IF EXISTS expires_at, DROP COLUMN IF EXISTS publish_at, DROP COLUMN IF EXISTS status, DROP COLUMN IF EXISTS cta_url, DROP COLUMN IF EXISTS cta_label, DROP COLUMN IF EXISTS image_url, DROP COLUMN IF EXISTS short_description;
DROP INDEX IF EXISTS uq_certificate_number;
ALTER TABLE certificates DROP COLUMN IF EXISTS pdf_content, DROP COLUMN IF EXISTS certificate_number, DROP COLUMN IF EXISTS template_id, DROP COLUMN IF EXISTS program_id;
DROP TABLE IF EXISTS certificate_rules;
DROP TABLE IF EXISTS certificate_templates;
ALTER TABLE approvals DROP COLUMN IF EXISTS updated_at, DROP COLUMN IF EXISTS reviewer_note, DROP COLUMN IF EXISTS note, DROP COLUMN IF EXISTS requested_by, DROP COLUMN IF EXISTS entity_id, DROP COLUMN IF EXISTS entity_type, DROP COLUMN IF EXISTS program_id;
DROP INDEX IF EXISTS idx_payments_program_status;
ALTER TABLE payments DROP COLUMN IF EXISTS updated_at, DROP COLUMN IF EXISTS notes, DROP COLUMN IF EXISTS installment_no, DROP COLUMN IF EXISTS due_date, DROP COLUMN IF EXISTS status, DROP COLUMN IF EXISTS program_id;
DROP TABLE IF EXISTS program_payment_settings;
ALTER TABLE documents DROP COLUMN IF EXISTS reviewed_at, DROP COLUMN IF EXISTS reviewed_by, DROP COLUMN IF EXISTS requirement_id;
DROP TABLE IF EXISTS document_requirements;
DROP INDEX IF EXISTS idx_pastoral_notes_participant;
DROP TABLE IF EXISTS pastoral_notes;
DROP INDEX IF EXISTS idx_journey_participant_date;
DROP TABLE IF EXISTS participant_journey_events;
COMMIT;
